### ISSUE TITLE
poll: should drop IE8 support?

### ISSUE THREAD

**Issue by futurist** [cssobj/cssobj#10]
Should cssobj drop old IE support? (IE<=8), mainly the **@media** hook

That's only 2 benefit I can see to **remove old IE @media hook**:

1. Smaller size ( before **4.2K min.gz**, after  **3.9K min.gz**

2. More maintainable code, the CSSOM plugin will be smaller, and more clearly.

The question:

1. do you use this feature now?

2. targeting IE>8, is that OK for you?

**Comment by rofrischmann** [comment]
IE8 is not even officially supported anymore. Guess no one is supporting IE8 today.:P You can even drop 9+10 after April 17th~ 2017, as support runs out for those as well.

**Comment by futurist** [comment]
@rofrischmann Thank you for the reply. If you live in China, the question is really a question... 1/3 of the computer here still running Windows XP...

Alibaba Inc., Chinese biggest e-biz website, still support IE8 till this year.

If I can make some perf improvement, due to the dropping of IE8, I'm definitely drop it. But now I can see it's not a perf problem, but some bundle size.

**Comment by PhiLhoSoft** [comment]
The fact Microsoft no longer supports a browser version doesn't mean it is no longer used... IE below 8 has to be dropped, it is not usable on the modern Internet anyway. IE 8 has still some world usage (3 % IIRC), so supporting it is still useful, at least for sites targeting a large user base.
Honestly, I am not sure that the size reduction is worth it; ease of maintenance is important, but since the code is already there...
Perhaps next year it will be worth asking again... 😄

**Comment by futurist** [comment]
Version 1.x will still keep the `@media IE8 hook`, IE8 still in the support list.

Any update of IE 8 support, will updated here in the future.
